language: node_js

node_js: stable

env:
  global:
    - GH_REF: github.com/foofuu/foofuu.github.io

before_install:
  - export TZ='Asia/Shanghai'  
  - npm install -g hexo
  - npm install -g hexo-cli
  - npm install hexo-util --save
  - npm install hexo-qiniu-sync --save
  - sed -i 's/Qiniu_AccessKey/${Qiniu_AccessKey}/' _config.yml
  - sed -i 's/Qiniu_SecretKey/${Qiniu_SecretKey}/' _config.yml

install:
  - npm install

cache:
  directories:
    - node_modules

script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "zhoufoofoo"
  - git config user.email "zhoujunfuv5@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

